config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: %i[ show edit update destroy ]

  # GET /pokemons or /pokemons.json
  def index
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1 or /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons or /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to pokemon_url(@pokemon), notice: "Pokemon was successfully created." }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1 or /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to pokemon_url(@pokemon), notice: "Pokemon was successfully updated." }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1 or /pokemons/1.json
  def destroy
    @pokemon.destroy

    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: "Pokemon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :element)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/_form.html.erb
<%= form_with(model: pokemon) do |form| %>
  <% if pokemon.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
        <% pokemon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :element, style: "display: block" %>
    <%= form.text_field :element %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemons/_pokemon.html.erb
<div id="<%= dom_id pokemon %>">
  <p>
    <strong>Name:</strong>
    <%= pokemon.name %>
  </p>

  <p>
    <strong>Element:</strong>
    <%= pokemon.element %>
  </p>

</div>

app/views/pokemons/edit.html.erb
<h1>Editing pokemon</h1>

<%= render "form", pokemon: @pokemon %>

<br>

<div>
  <%= link_to "Show this pokemon", @pokemon %> |
  <%= link_to "Back to pokemons", pokemons_path %>
</div>

app/views/pokemons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pokemons</h1>

<div id="pokemons">
  <% @pokemons.each do |pokemon| %>
    <%= render pokemon %>
    <p>
      <%= link_to "Show this pokemon", pokemon %>
    </p>
  <% end %>
</div>

<%= link_to "New pokemon", new_pokemon_path %>

app/views/pokemons/new.html.erb
<h1>New pokemon</h1>

<%= render "form", pokemon: @pokemon %>

<br>

<div>
  <%= link_to "Back to pokemons", pokemons_path %>
</div>

app/views/pokemons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pokemon %>

<div>
  <%= link_to "Edit this pokemon", edit_pokemon_path(@pokemon) %> |
  <%= link_to "Back to pokemons", pokemons_path %>

  <%= button_to "Destroy this pokemon", @pokemon, method: :delete %>
</div>